
    CREATE TABLE "FLYWAY"."schema_version"   (
        	"installed_rank" NUMBER(*,0) NOT NULL ENABLE,
       	"version" VARCHAR2(50),
       	"description" VARCHAR2(200) NOT NULL ENABLE,
       	"type" VARCHAR2(20) NOT NULL ENABLE,
       	"script" VARCHAR2(1000) NOT NULL ENABLE,
       	"checksum" NUMBER(*,0),
       	"installed_by" VARCHAR2(100) NOT NULL ENABLE,
       	"installed_on" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
       	"execution_time" NUMBER(*,0) NOT NULL ENABLE,
       	"success" NUMBER(1,0) NOT NULL ENABLE,
       	 CONSTRAINT "schema_version_pk" PRIMARY KEY ("installed_rank")  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)  TABLESPACE "SYSTEM"  ENABLE   
    ) SEGMENT CREATION IMMEDIATE  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING  STORAGE(
        INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    )  TABLESPACE "SYSTEM"